version: "3.8"
services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d/"
      - "./mysql_files:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plexdb
      MYSQL_USER: plexuser
      MYSQL_PASSWORD: plexpwd

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 

  php:
    restart: always
    build: ./engine/php_server/
    volumes:
      - "./html:/var/www/html"
    depends_on:
      - db
    links:
      - "db"
    ports: 
      - "80:80"
    dns:
    - 208.67.222.222
    - 208.67.220.220

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
    volumes:
      - ./plex_config:/config
      - ./tv:/tv
      - ./movies:/movies
    restart: unless-stopped