version: "3.8"
services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - "./db/mysql:/docker-entrypoint-initdb.d/"
      - "./db/mysql_files:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plexdb
      MYSQL_USER: plexuser
      MYSQL_PASSWORD: plexpwd

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 

  php:
    restart: always
    build: ./engine/php_server/
    volumes:
      - "./engine/html:/var/www/html"
    depends_on:
      - db
    links:
      - "db"
    ports: 
      - "80:80"
    dns:
    - 208.67.222.222
    - 208.67.220.220

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    ports:
      - "32400:32400"
    volumes:
      - ./plex/config:/config
      - ./downloads/complete/tv:/data/tv
      #- ./plex/movies:/movies
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: always
    ports: 
      - "8112:8112"
    volumes:
      - ./downloads:/downloads # downloads folder
      - ./deluge/config:/config # config files
  
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports: 
      - "9117:9117"
    volumes:
      - ./downloads/torrent-blackhole:/downloads/ # place where to put .torrent files for manual download
      - ./jackett/config:/config/Jackett # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
     - "8989:8989"
    volumes:
     - ./sonarr/config:/config # config files
     - ./downloads/complete/tv:/tv # tv shows folder
     - ./downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
     - "7878:7878"
    volumes: 
     - ./radarr/config:/config
     - ./downloads/complete/movies:/movies
     - ./downloads:/downloads