version: "3.8"
services:

  db:
    image: mysql
    restart: always
    volumes: 
      - "./db:/etc/mysql/conf.d/mysqld_charset.cnf"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: plexuser
      MYSQL_PASSWORD: passw0rd
      MYSQL_DATABASE: plexdb
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes: 
      - "./phpmyadmin:/etc/phpmyadmin"
    depends_on:
      - db
    links:
      - db
    ports: 
      - "8181:80"
    environment:
        MYSQL_USER: plexuser
        MYSQL_PASSWORD: passw0rd 
        MYSQL_ROOT_PASSWORD: root

  php:
    restart: always
    build: ./engine/php_server/
    volumes:
      - ".html:/var/www/html"
    depends_on:
      - db
    links:
      - "db"
    ports: 
      - "80:80"
    dns:
    - 208.67.222.222
    - 208.67.220.220